#cloud-config

users:
  - name: dalton
    groups: sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
%{ for key in ssh_public_keys ~}
      - ${key}
%{ endfor ~}

package_update: true
package_upgrade: true
ssh_pwauth: false

packages:
  - qemu-guest-agent
  - nfs-common
  - open-iscsi
  - curl
  - apt-transport-https

runcmd:
  - systemctl enable --now qemu-guest-agent
  - systemctl enable --now iscsid