#cloud-config

users:
  - name: dalton
    groups: sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
%{ for key in ssh_public_keys ~}
      - ${key}
%{ endfor ~}

package_update: true
package_upgrade: true
ssh_pwauth: false

packages:
  - qemu-guest-agent
  - nfs-kernel-server

runcmd:
  - systemctl enable --now qemu-guest-agent
  - mkdir -p /srv/nfs/k8s
  - echo '/srv/nfs/k8s 192.168.40.0/24(rw,sync,no_subtree_check,no_root_squash)' >> /etc/exports
  - exportfs -ra
  - systemctl enable --now nfs-server